#!/usr/bin/env bash
# Generate commands.sh — one line per WitchyBND.exe invocation, each batched
# so the line stays under the Windows command-line character limit.
#
# To minimize per-line character count, the generated commands.sh:
#   - cd's into $MSB_DIR once at the top,
#   - refers to each map file by basename only,
#   - uses a path to WitchyBND.exe relativized to $MSB_DIR when shorter.
#
# Batch size is auto-computed from the prefix length (WitchyBND path + space),
# the longest filename, and CMDLINE_LIMIT (default 8000, the cmd.exe limit).
# Override via env: CMDLINE_LIMIT=32000 ./scripts/generate_witchy_commands.sh
#
# Run from the repo root:
#     ./scripts/generate_witchy_commands.sh
#     ./scripts/commands.sh
#
# Requires WITCHYBND_EXE and MSB_DIR in .env (see .env.example).

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
ENV_FILE="$REPO_ROOT/.env"
if [[ -f "$ENV_FILE" ]]; then
  set -a
  # shellcheck disable=SC1090
  source "$ENV_FILE"
  set +a
fi

: "${WITCHYBND_EXE:?WITCHYBND_EXE must be set in .env (path to WitchyBND.exe)}"
: "${MSB_DIR:?MSB_DIR must be set in .env (path to the mapstudio directory)}"

if [[ ! -f "$WITCHYBND_EXE" ]]; then
  echo "WITCHYBND_EXE not found: $WITCHYBND_EXE" >&2
  exit 1
fi
if [[ ! -d "$MSB_DIR" ]]; then
  echo "MSB_DIR not found: $MSB_DIR" >&2
  exit 1
fi

CMDLINE_LIMIT="${CMDLINE_LIMIT:-8000}"
OUTPUT="$SCRIPT_DIR/commands.sh"

# Prefer a WitchyBND.exe path relative to MSB_DIR when it shortens the command.
WITCHYBND_REL="$(realpath --relative-to="$MSB_DIR" "$WITCHYBND_EXE" 2>/dev/null || true)"
if [[ -n "$WITCHYBND_REL" && ${#WITCHYBND_REL} -lt ${#WITCHYBND_EXE} ]]; then
  WITCHYBND_USE="$WITCHYBND_REL"
else
  WITCHYBND_USE="$WITCHYBND_EXE"
fi

# Collect map files as basenames only — commands.sh will cd into MSB_DIR first.
mapfile -d '' -t MSB_FILES < <(find "$MSB_DIR" -maxdepth 1 -type f -name "*.msb.dcx" -printf '%f\0')

if (( ${#MSB_FILES[@]} == 0 )); then
  echo "No .msb.dcx files found in $MSB_DIR" >&2
  exit 1
fi

# Auto-size the batch: longest filename + 1 (space separator), plus the prefix.
MAX_NAME=0
for f in "${MSB_FILES[@]}"; do
  (( ${#f} > MAX_NAME )) && MAX_NAME=${#f}
done

PREFIX_LEN=$(( ${#WITCHYBND_USE} + 1 ))    # exe + trailing space
BUDGET=$(( CMDLINE_LIMIT - PREFIX_LEN ))
FILES_PER_CALL=$(( BUDGET / (MAX_NAME + 1) ))

if (( FILES_PER_CALL < 1 )); then
  echo "CMDLINE_LIMIT=$CMDLINE_LIMIT is too small for prefix '$WITCHYBND_USE' + a single filename ($MAX_NAME chars)" >&2
  exit 1
fi

{
  echo "#!/usr/bin/env bash"
  echo "# Generated by scripts/generate_witchy_commands.sh — do not edit."
  echo "set -e"
  printf 'cd %q\n' "$MSB_DIR"
  printf '%s\n' "${MSB_FILES[@]}" \
    | xargs -n "$FILES_PER_CALL" echo "$WITCHYBND_USE"
} > "$OUTPUT"

chmod +x "$OUTPUT"

CMD_COUNT=$(($(wc -l < "$OUTPUT") - 4))
WORST_LINE=$(( PREFIX_LEN + FILES_PER_CALL * (MAX_NAME + 1) - 1 ))
echo "Generated $CMD_COUNT WitchyBND invocations over ${#MSB_FILES[@]} files in $OUTPUT"
echo "  cwd:         $MSB_DIR"
echo "  exe:         $WITCHYBND_USE"
echo "  batch size:  $FILES_PER_CALL (auto; longest name=$MAX_NAME, limit=$CMDLINE_LIMIT, worst line ≈ $WORST_LINE chars)"
echo "Run with: ./scripts/commands.sh"
